version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rails_test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@postgres:5432/rails_test"
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: your_primary_key
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: your_deterministic_key
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: your_salt
    depends_on:
      - postgres
    # The container will exit after running the tests
    command: ["bundle", "exec", "rspec"]
